import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { remark } from "remark";
import html from "remark-html";
import {
  describeUpdate,
  formatDate,
  formatEpochRange,
  getAllEditions,
  getEdition,
  getHighlights,
  groupByCategory,
  showsEveryChangeByDefault,
  summaryParts,
  type Edition,
  type RevisionChange,
} from "@/lib/revisions";

export async function generateStaticParams() {
  return getAllEditions().map((edition) => ({ edition: edition.editionId }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ edition: string }>;
}): Promise<Metadata> {
  const { edition: editionId } = await params;
  const edition = getEdition(editionId);
  if (!edition) return { title: "Revisions" };
  return {
    title: formatEpochRange(edition),
    description: `${edition.changeCount} reference-data ${
      edition.changeCount === 1 ? "change" : "changes"
    } between published epoch ${edition.from.epoch} and ${edition.to.epoch}.`,
  };
}

const KIND_LABEL: Record<string, string> = {
  added: "Added",
  removed: "Removed",
  updated: "Refined",
};

function ChangeRow({ change }: { change: RevisionChange }) {
  return (
    <li
      style={{
        display: "flex",
        gap: "0.75rem",
        alignItems: "baseline",
        padding: "0.4rem 0",
        borderBottom: "1px solid var(--atlas-separator)",
      }}
    >
      <span
        style={{
          flex: "0 0 4.5rem",
          fontSize: "0.75rem",
          letterSpacing: "0.04em",
          textTransform: "uppercase",
          color: "var(--atlas-text-placeholder)",
        }}
      >
        {KIND_LABEL[change.kind] ?? change.kind}
      </span>
      <span style={{ flex: 1, fontSize: "0.925rem", color: "var(--atlas-text)" }}>
        {change.label}
        {change.kind === "updated" && (
          <span
            style={{
              color: "var(--atlas-text-secondary)",
              fontSize: "0.85rem",
            }}
          >
            {" "}
            — {describeUpdate(change)}
          </span>
        )}
      </span>
    </li>
  );
}

function ChangeList({ changes }: { changes: RevisionChange[] }) {
  return (
    <>
      {groupByCategory(changes).map((group, index) => (
        <div key={`${group.category}-${index}`} style={{ marginBottom: "2rem" }}>
          <h3
            style={{
              fontSize: "0.8rem",
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              color: "var(--atlas-text-placeholder)",
              marginBottom: "0.5rem",
            }}
          >
            {group.category}
          </h3>
          <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
            {group.changes.map((change) => (
              <ChangeRow
                key={`${change.category}-${change.kind}-${change.id}`}
                change={change}
              />
            ))}
          </ul>
        </div>
      ))}
    </>
  );
}

function Endpoints({ edition }: { edition: Edition }) {
  return (
    <div
      style={{
        marginTop: "3rem",
        paddingTop: "1.5rem",
        borderTop: "1px solid var(--atlas-separator)",
        fontSize: "0.75rem",
        lineHeight: 1.7,
        color: "var(--atlas-text-placeholder)",
      }}
    >
      <p style={{ marginBottom: "0.5rem" }}>
        Generated by comparing the two published reference-data epochs below. Every
        entry above is derived from those two snapshots.
      </p>
      {[edition.from, edition.to].map((endpoint, index) => (
        <div key={endpoint.commit} style={{ fontFamily: "ui-monospace, monospace" }}>
          {index === 0 ? "from" : "to"} · epoch {endpoint.epoch} ·{" "}
          {endpoint.commit.slice(0, 12)} · registry{" "}
          {endpoint.registrySha256.slice(0, 12)}
        </div>
      ))}
    </div>
  );
}

export default async function EditionPage({
  params,
}: {
  params: Promise<{ edition: string }>;
}) {
  const { edition: editionId } = await params;
  const edition = getEdition(editionId);
  if (!edition) notFound();

  const highlightsMarkdown = getHighlights(editionId);
  const highlightsHtml = highlightsMarkdown
    ? (await remark().use(html).process(highlightsMarkdown)).toString()
    : null;
  const showAll = showsEveryChangeByDefault(edition);

  return (
    <section style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px 80px" }}>
      <Link
        href="/revisions"
        style={{
          fontSize: "0.8rem",
          color: "var(--atlas-text-secondary)",
          textDecoration: "none",
        }}
      >
        ← Revisions
      </Link>

      <h1
        style={{
          fontSize: "1.8rem",
          fontWeight: 600,
          letterSpacing: "-0.02em",
          color: "var(--atlas-text)",
          margin: "1.5rem 0 0.4rem",
        }}
      >
        {formatEpochRange(edition)}
      </h1>
      <p
        style={{
          fontSize: "0.8rem",
          color: "var(--atlas-text-placeholder)",
          marginBottom: "2.5rem",
          letterSpacing: "0.02em",
        }}
      >
        {formatDate(edition.to.committedAt)} ·{" "}
        {edition.changeCount === 1 ? "1 change" : `${edition.changeCount} changes`}
      </p>

      {highlightsHtml && (
        <div
          style={{
            backgroundColor: "var(--atlas-card)",
            border: "1px solid var(--atlas-card-stroke)",
            borderRadius: 4,
            padding: "1.25rem 1.5rem",
            marginBottom: "2.5rem",
          }}
        >
          <h2
            style={{
              fontSize: "0.8rem",
              letterSpacing: "0.06em",
              textTransform: "uppercase",
              color: "var(--atlas-text-placeholder)",
              marginBottom: "0.75rem",
            }}
          >
            Highlights
          </h2>
          <div
            className="revisions-highlights"
            style={{
              fontSize: "0.95rem",
              lineHeight: 1.65,
              color: "var(--atlas-text)",
            }}
            dangerouslySetInnerHTML={{ __html: highlightsHtml }}
          />
          <p
            style={{
              marginTop: "1rem",
              fontSize: "0.75rem",
              color: "var(--atlas-text-placeholder)",
            }}
          >
            Written by hand. The record below is generated from the epochs and is not
            affected by this note.
          </p>
        </div>
      )}

      {edition.changeCount === 0 ? (
        <p style={{ fontSize: "0.925rem", color: "var(--atlas-text-secondary)" }}>
          No reference-data changes were published in this epoch.
        </p>
      ) : showAll ? (
        <ChangeList changes={edition.changes} />
      ) : (
        <>
          <ul
            style={{
              listStyle: "none",
              padding: 0,
              margin: "0 0 2rem",
            }}
          >
            {edition.categories.map((summary) => (
              <li
                key={summary.category}
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: "1rem",
                  padding: "0.5rem 0",
                  borderBottom: "1px solid var(--atlas-separator)",
                  fontSize: "0.925rem",
                  color: "var(--atlas-text)",
                }}
              >
                <span>{summary.category}</span>
                <span style={{ color: "var(--atlas-text-secondary)" }}>
                  {summaryParts(summary).join(" · ")}
                </span>
              </li>
            ))}
          </ul>
          <details>
            <summary
              style={{
                cursor: "pointer",
                fontSize: "0.875rem",
                color: "var(--atlas-tint)",
                marginBottom: "1.5rem",
              }}
            >
              All {edition.changeCount} changes
            </summary>
            <ChangeList changes={edition.changes} />
          </details>
        </>
      )}

      <Endpoints edition={edition} />
    </section>
  );
}
